### ISSUE TITLE
Error:(10, 15) Kotlin: Missing 'getValue(CUSTOMER, KProperty<*>)' method on delegate of type 'Column<Int>'

### ISSUE THREAD

**Issue by Yadarma** [edvin/kdbc#12]
Hey Edvin, Trying to code like this:
```
import kdbc.Table

class CUSTOMER : Table("customer") {
*    val id by column { getInt(it) }
*    val name by column { getString(it) }
}

data class customer(
        var id: Int,
        var name: String,
        var zip: String,
        var city: String
)
```
compile-error at `*`-lines:
Error:(10, 15) Kotlin: Missing 'getValue(CUSTOMER, KProperty<*>)' method on delegate of type 'Column<Int>' ???

**Comment by edvin** [comment]
Try to import `kdbc.*` :)

**Comment by Yadarma** [comment]
Still the same error :)

**Comment by edvin** [comment]
Sorry, the syntax was changed because it proved inflexible. I've updated the examples in the README now. `val id = column<Int>("id")` is the new syntax.

**Comment by Yadarma** [comment]
It worked. Thanks for your support 👍

**Comment by edvin** [comment]
Great! Glad to hear it :)

**Comment by Yadarma** [comment]
```
data class Customer(
    var id: Int,
    var name: String,
    var zip: String,
    var city: String
)
class SelectCustomer : Query<Customer> {
    val c = CUSTOMER()

    init {
        select(c.id, c.name, c.zip, c.city)
        from(c)
    }

    **override fun get() = Customer(c.id(), c.name(), c.zip(), c.city())
}
```
`**`-line gave me error "Error:(29, 31) Kotlin: Type mismatch: inferred type is Int? but Int was expected"

I made it like `c.name().tostring` and it worked. Should I make it like that?? I am just obviously cheating out of the Read me code :)
